title = "GenMed"
baseURL = "https://GenMed.github.io/"
languageCode = "en-us"

theme = ["ananke"]

DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 6 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  favicon = ""
  site_logo = "/images/logo1.png"
  description = "BioMedical and Machine Learning group at the University of Jordan."
  facebook = ""
  twitter = "https://twitter.com/ElbragYouness"
  instagram = ""
  youtube = ""
  github = "https://github.com/GenMed"
  gitlab = ""
  linkedin = ""
  mastodon = ""
  slack = ""
  stackoverflow = ""
  rss = ""
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-dark-green"
  featured_image = "/images/DIKU.jpg"
  recent_posts_number = 2

[markup.goldmark.renderer]
  unsafe = true
